"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Brad Robinson"
email = "31802085+bnrobinson93@users.noreply.github.com"

[aliases]
s = "status"
l = ["log", "--limit", "15"]
push = ["git", "push", "--allow-new"]
tug = ["bookmark", "move", "--to", "@-"] # for the new + tug + squash workflow

[commit]
sign = true

[ui]
default-command  = ["log", "--limit", "15", "-T", "change_id.shortest(8) ++ ' - ' ++ label('bookmark', if(bookmarks, '(' ++ bookmarks.join(', ') ++ ') ', '')) ++ coalesce(description.first_line(), '(empty)') ++ ' ' ++ label('timestamp', '(' ++ committer.timestamp().ago() ++ ')') ++ ' ' ++ label('author', '<' ++ author.name() ++ '>') ++ ' ' ++ if(signature, label('signature', ' '), label('unsigned', ' '))"]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
merge-editor = ["meld", "$left", "$base", "$right", "-o", "$output"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[colors]
signature = "green"
unsigned = "red"

# this will be lazily signed again before pushing with sign-on-push; else use "own" to sign all changes
# It would be nice to use "own" istead of "drop"
[signing]
behavior = "own"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOIidIqt1fDMmhx1KUyCyKduIJCcJMhQk+f5vd6JEjsO"
backend = "ssh"

[core]
excludesfile = "~/.gitignore"

[signing.backends.ssh]
# program = "ssh-sign-wrapper.sh"
program = "ssh-sign-wrapper.sh"
allowed_signers = "~/.ssh/allowed_signers"

[git]
auto-local-bookmark = true
sign-on-push = true

[templates]
git_push_bookmark = '"" ++ change_id.short()'
