import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
blur = true
dynamic_title = true

[font]
size = 15
normal.family = "DankMono Nerd Font"

# Fixes tmux bg
[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style.blinking = "On"
