scan_timeout = 10
command_timeout = 500

format = """$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$package\
$golang\
$nodejs\
$jobs\
$character"""

# format_right = """$all"""
palette = "catppuccin_mocha"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
disabled = true

[directory]
style = "green"
truncation_length = 5
truncate_to_repo = false
# fish_style_pwd_dir_length = 1

[gcloud]
detect_env_vars = ["GCP_PROJECT", "CLOUDSDK_CORE_PROJECT"]
timeout = 500

[git_state]
format = '[ \($state( $progress_current of $progress_total)\)]($style)'
style = 'bold teal'

[git_branch]
symbol = " "
style = 'sky'
format = """on [$symbol$branch(:$remote_branch)]($style)"""
only_attached = true

[git_metrics]
disabled = true

[git_status]
conflicted = '[󰀨 ](red)'
ahead = "[󰳡 ](flamingo)"
behind = "[󰳛 ](blue)"
diverged = "[󰵚 ](orange)"
untracked = "[󰋗 ](yellow)"
stashed = "[󰓏 ](lavender)"
modified = "[󰛿 ](peach)"
staged = "[󰐗 ](green)"
renamed = "[󰁙 ](rose)"
deleted = '[󰅙 ](red)'
format = '([ $all_status$ahead_behind]($style) )'
ignore_submodules = true

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = ["package.json"]
detect_folders = []
detect_extensions = []

[package]
format = "[📦 $version ](flamingo)"

[jobs]
style = "surface2"

[golang]
symbol = " "
detect_files = ["go.mod", "go.sum"]
detect_folders = []
detect_extensions = []

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Disable slow/unused modules for better performance
[aws]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[memory_usage]
disabled = true

[python]
disabled = true
