# Extra autostart processes
#exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- hyprsunset

windowrule {
  name = ticktick
  match:initial_title = ticktick\.com.*
  workspace = special:scratchpad silent
}
windowrule {
  name = google-messages
  match:initial_title = messages\.google\.com.*
  workspace = special:scratchpad silent
}
 
exec-once = helium-browser --app="https://ticktick.com/webapp"
exec-once = helium-browser --app="https://messages.google.com/web"
