return {
  {
    "MeanderingProgrammer/render-markdown.nvim",
    priority = 1000,
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    ft = { "markdown", "Avante", "vimwiki", "help", "copilot-chat" },
    opts = {
      file_types = { "markdown", "Avante" },
      render_modes = { "n", "c", "t" },
      checkbox = {
        enabled = true,
        unchecked = { icon = " " },
        checked = { icon = "󰄳 ", scope_highlight = "@markup.strikethrough" },
        custom = {
          canceled = { raw = "[-]", rendered = " ", highlight = "DiagnosticSignError" },
          in_progress = { raw = "[/]", rendered = " ", highlight = "DiagnosticSignHint" },
          partial = { raw = "[~]", rendered = " ", highlight = "DiagnosticSignHint" },
          important = { raw = "[!]", rendered = "󰓏 ", highlight = "DiagnosticSignWarn" },
          star = { raw = "[*]", rendered = "󰓏 ", highlight = "DiagnosticSignWarn" },
          migrated = { raw = "[>]", rendered = " ", highlight = "DiagnosticSignWarn" },
          scheduled = { raw = "[<]", rendered = "󰥔 ", highlight = "DiagnosticSignWarn" },
          question = { raw = "[?]", rendered = " ", highlight = "Constant" },
          note = { raw = "[n]", rendered = "󰐃 ", highlight = "Special" },
          location = { raw = "[l]", rendered = " ", highlight = "Include" },
          info = { raw = "[i]", rendered = " ", highlight = "FloatBorder" },
          idea = { raw = "[I]", rendered = "󰌵 ", highlight = "Structure" },
          amount = { raw = "[s]", rendered = " ", highlight = "Added" },
          pro = { raw = "[p]", rendered = "󰔓 ", highlight = "Added" },
          con = { raw = "[c]", rendered = "󰔑 ", highlight = "DiagnosticSignError" },
          bookmark = { raw = "[b]", rendered = " ", highlight = "DiagnosticSignError" },
          quote = { raw = '["]', rendered = "󰝗 ", highlight = "DiagnosticUnnecessary" },
          up = { raw = "[u]", rendered = "󰔵 ", highlight = "Added" },
          down = { raw = "[d]", rendered = "󰔳 ", highlight = "DiagnosticSignError" },
          win = { raw = "[w]", rendered = " ", highlight = "Define" },
          key = { raw = "[k]", rendered = " ", highlight = "DiagnosticSignWarn" },
          fire = { raw = "[f]", rendered = "󰈸 ", highlight = "DiagnosticSignError" },
          partial_parent = {
            raw = "[+]",
            rendered = "󰁊 ",
            highlight = "DiagnosticDepricated",
            scope_highlight = "@markup.strikethrough",
          },
        },
      },
      pipe_table = {
        enabled = true,
        cell = "trimmed",
        preset = "round",
      },
    },
  },
}
